version: "3.3"

volumes:
  - postgres

services:

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    image: "${IMAGE_TAG}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      HOST: "${HOST}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
