version: "3.3"

volumes:

  - postgres

networks:

  traefik_http:
    external: true

services:

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: app
    volumes:
      - postgres:/var/lib/postgresql/data

  web:
    image: "${IMAGE_TAG}"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      HOST: "${HOST}"
      SECRET_KEY_BASE: "${SECRET_KEY_BASE}"
    networks:
      - traefik_http
    deploy:
      labels:
        traefik.docker.network: traefik_http
        traefik.frontend.rule: "Host:${HOST}"
        traefik.port: 4000
