FROM nolan/alpine-erlang:20.0.1

RUN apk update && \
    apk --no-cache --update add libgcc libstdc++ libsodium && \
    rm -rf /var/cache/apk/*

EXPOSE 4000
ENV PORT=4000 MIX_ENV=prod REPLACE_OS_VARS=true SHELL=/bin/sh

ADD app.tar.gz ./
RUN chown -R default ./releases

USER default

ENTRYPOINT ["/opt/app/bin/app"]
CMD foreground
